// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg26v1vi-7w5ME-N0s3MOxQaSnxNq6LtY',
    appId: '1:207169793598:web:3535d3ebac027c96b2ab6f',
    messagingSenderId: '207169793598',
    projectId: 'finalproject-b0bdf',
    authDomain: 'finalproject-b0bdf.firebaseapp.com',
    storageBucket: 'finalproject-b0bdf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpcKrhLR0AfK2uPkFn3YdsIDd7XmalPow',
    appId: '1:207169793598:android:2f6b953925d9e2f3b2ab6f',
    messagingSenderId: '207169793598',
    projectId: 'finalproject-b0bdf',
    storageBucket: 'finalproject-b0bdf.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDenHkko2LFHWkGqDPCVRqgu6AnL8I6X-g',
    appId: '1:207169793598:ios:72d32f454181de69b2ab6f',
    messagingSenderId: '207169793598',
    projectId: 'finalproject-b0bdf',
    storageBucket: 'finalproject-b0bdf.appspot.com',
    iosClientId: '207169793598-s5k07ds5dpjsamgu60gmnagfp4v1deph.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDenHkko2LFHWkGqDPCVRqgu6AnL8I6X-g',
    appId: '1:207169793598:ios:72d32f454181de69b2ab6f',
    messagingSenderId: '207169793598',
    projectId: 'finalproject-b0bdf',
    storageBucket: 'finalproject-b0bdf.appspot.com',
    iosClientId: '207169793598-s5k07ds5dpjsamgu60gmnagfp4v1deph.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg26v1vi-7w5ME-N0s3MOxQaSnxNq6LtY',
    appId: '1:207169793598:web:45ac211cf44b3de4b2ab6f',
    messagingSenderId: '207169793598',
    projectId: 'finalproject-b0bdf',
    authDomain: 'finalproject-b0bdf.firebaseapp.com',
    storageBucket: 'finalproject-b0bdf.appspot.com',
  );

}